spring:
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name : com.mysql.jdbc.Driver
     url : jdbc:mysql://localhost:3306/cloud_template?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
     username : root
     password : m123
  cloud:
    stream:
      rabbit:
        binder:
          nodes: localhost:5672
      default-binder: rabbit
logging:
  level:
    org.hswebframework.web: DEBUG
    org.hswebframework.web.cache: WARN
    org.bestfeng: DEBUG
    org.apache.ibatis: DEBUG
    org.mybatis: DEBUG


